### PR TITLE
Bug/unique constraint

### PR DESCRIPTION
**Pull request by roll**
fix https://github.com/frictionlessdata/goodtables/issues/101#issuecomment-219991763

### CODE REVIEW

**Comment by roll** [comment]
@georgiana-b 
could you please review?

**Comment by georgiana-b** [comment]
IMO it was more transparent to raise the error because the README clearly states `Note: the unique constraint is not currently supported` and returning `True` might give the wrong impression and cause more trouble. I think clients should deal with the fact that it's not implemented, which is why I opened frictionlessdata/goodtables#101. However, it's your call.

**Comment by georgiana-b** [comment]
@roll I'm thinking that since I have to implement the functionality for `unique` constraint in GoodTables, I might as well do it here. So, why is it not implemented yet? Is it just a matter of priorities?

**Comment by roll** [comment]
@georgiana-b 
Don't see it's possible with current cast system design. It should be somewhere on model layer I suppose.

**Comment by roll** [comment]
I've updated PR to skip `unique` constraint on `JTSType.cast` level because on this level it anyway shouldn't be checked (not enough information).

**Comment by georgiana-b** [comment]
@roll Sorry, I'm not yet familiar enough with this project to give feedback. I'll check out the code and come back with suggestions if I have any.

**Comment by roll** [comment]
@georgiana-b 
I think `unique` constraint on this codebase is something big (I've added comment to the issue) so @pwalsh will actualize it later

**Pull request merged**
