### PR TITLE
Feature/Renewed API

### LINKED ISSUE #34: Make the model class better
* Consistency in naming and access (data vs meta data, etc.)
* Data methods ( https://github.com/okfn/jsontableschema-py/blob/master/jsontableschema/model.py#L186-L221 ) should use `tabulator-py`

### LINKED ISSUE #60: Make output API stricter
For example `schema.json` could have `primaryKey` as `value` or `list of values` but `jsontableschema.model.SchemaModel.primaryKey` should always be `list` because otherwise it's hard to work with such an interface (for now it's just to proxy value or list from the schema).

The same for some other parts (to discover).

---

- [ ] make output API stricter

### LINKED ISSUE #70: Storage: add schema argument to describe?
> This is big so a good idea to start on it in sync with - https://github.com/frictionlessdata/jsontableschema-py/issues/34

Problem in a few words - to work with JTS in a full strength `Storage` should have not only **reflected** schema (from SQL table for example) but also **original** one (because reflection doesn't know anything about date patterns etc - it will be failing on write e.g.). Current situation could be improved with some approaches:
- pass schema to some methods
- rebase on atomic operations
- store schema in backend 

---

We could add optional `schema` arg to `Storage.describe(schema)` to override reflected schema by user-defined. So `storage` instance will be have it internally.

---

We could add optional `schema` argument to `Storage.write/read` so data from table without appropriate schema reflection could be cast:

```python
storage.read('table', schema)
# will return cast data
```

The same rationale for `Storage.write` about writing data.

---

More radical approach will be replace `Storage.create/write/read` with **atomic** `Storage.push/pull`. It could simplify many things and based on this - https://github.com/frictionlessdata/datapackage-py/issues/69#issuecomment-215685065 - it fits better with main use cases. But it will be breaking.

---

We could store schemas in the storage (in the meta table _schemas for example). It's not against current design and could be implemented relatively fast. For tables not having _schemas current reflection system is still be working with subset of features supported. So user still will be able to describe and read just a SQL table (the same as now).

---

Really related - frictionlessdata/datapackage-py#69

### LINKED ISSUE #71: Storage: drivers should return cast data
Requires https://github.com/frictionlessdata/jsontableschema-py/issues/70

---

After this https://github.com/frictionlessdata/jsontableschema-py/issues/59 is fixed now it's possible to cast values returned by drivers to their canonical form.

Example:
- for now sql driver returns `float` for numbers
- sql driver should return `decimal.Decimal` for numbers

### LINKED ISSUE #72: Storage: drivers should store unsupported types as strings
Requires https://github.com/frictionlessdata/jsontableschema-py/issues/70

### LINKED ISSUE #78: Add a class for data + schema
# Overview

On a JSON Table schema level we miss one important concept - schema + data instance.

# Analysis

Initial analysis have found that as first we should try to implement `jsonableschema.Table` and use it in `datapackage.Resource` instead of having resource concept on JTS level (I'll expand this after prototyping).

# Tasks

- [x] requires https://github.com/frictionlessdata/tabulator-py/issues/35
- [ ] ...

### LINKED ISSUE #86: Storage: add force/ignore arguments to delete/create
# Overview

This boilerplate code we use a lot:

```
if storage.check(table):
    storage.delete(table)
storage.create(table, schema)
```

Could be:

```
storage.create(table, schema, force=True)
```

To delete ignore not existent:

```
storage.delete(table, ignore=True)
```

### LINKED ISSUE #87: Storage: read should read into memory, add iter
# Overview

For now `Storage.read` acts like `iter` in other FD packages. So we need both:
- `iter` to iterate over rows
- `read` to read into memory with optional `limit` of rows count

### LINKED ISSUE #88: Storage: make table argument in delete optional
# Overview

So there will be `delete all` action.

### LINKED ISSUE #89: Storage: better docstrings, update naming?
# Overview

We have storage interface here only as a reference so it should be documented better esp `Storage.tables` which should return table names base on dependencies resolution order (FK in SQL).

# Tasks

- [ ] docs
- [ ] data->rows
- [ ] rename `tables/table`? (base on FD stack reference)

### LINKED ISSUE #91: Fix readme on PyPi
# Overview

Readme is expected to be in RST. See solution - https://github.com/frictionlessdata/jsontableschema-pandas-py

### LINKED ISSUE #92: Storage: remove interface inheritance from backends
# Overview

In python interface implementation technically means too less (could be incompatible with method signatures etc) so better to remove `Storage` class inheritance from drivers. Having it will prevent `Storage` interface extending.

We need to use it only for documentation purposes (here interface implementation concept is very important).

### LINKED ISSUE #93: Rebase Table.write on tabulator write mode when it will be available
# Overview

For now only csv is supported.

https://github.com/frictionlessdata/tabulator-py/issues/36

### LINKED ISSUE #97: Add an interface to update table processors?
# Overview

Working with table directly an user could set `post_parse/post_convert` processor using class constructor. But if table has been created by datapackage library for instance? Probably we need an additional method to add processors.

Something like:
```
table.post_convert = [...]
table.stream.post_parse = [...]
```

### LINKED ISSUE #101: Table: use storage.describe(bucket, schema) when will be available on drivers
TBD

### LINKED ISSUE #102: Table: discover possibility to wrap storage in stream interface
# Overview

It means instead having both `Table.__stream` and `Table.__storage` (one of them always None) `storage` could be converted to `stream` using tabulator wrap.

Requires https://github.com/frictionlessdata/tabulator-py/issues/82

### PR DESCRIPTION
**Pull request by roll**
# Overview

Here is a renewed API for `jsontableschema`.

# Issues

- fixes #34 
- fixes #60 
- fixes #78 
- fixes #87 
- fixes #89 
- fixes #70 
- fixes #86 
- fixes #88
- fixes #71 
- fixes #72 
- fixes #92 
- fixes #93 
- fixes #91
- fixes #101
- fixes #102 
- fixes #97

# API plan

https://github.com/frictionlessdata/project/issues/289

# jsontableschema.Field

It's a new class to cover `field` concept. Instances available are as `schema.fields`. For now it's just for convenience (much easier to work with field object than with field dict always checking key existence etc. Also `convert_value` moved here because it's field responsibility. Later to `Field` could be moved some `types` functionality while `types` will start act as a general data parsers. 

# jsontableschema.Schema

This class just cleans the API of old `model.SchemaModel` making it in sync with FD stack reference plan ans `jsontableschema-js`.

# jsontableschema.Table

Data + schema class. Why not `Resource`? Resource is a `datapackage` level concept. Resource should work using resource descriptor `resource = Resource(descriptor)` supporting all features from datapackage specification. Here on JSON Table Level we works with tables so we don't need to handle all this stuff (but we need to integrate here tabulator+storage backends). But if datapackage resource could be represented as JSON Table Schema table it should have `resource.table=jsontableschema.Table()`  attribute.

For now `Table` already includes all `pull/push_resource` functionality. After tabulator write mode will be ready we could be able to save to other formats like `xls` etc.

Working example:
```python
import sqlalchemy as sa
from jsontableschema import Table

# Create SQL database
db = sa.create_engine('sqlite://')

# Data from WEB, schema from MEMORY
SOURCE = 'https://raw.githubusercontent.com/okfn/jsontableschema-py/master/data/data_infer.csv'
SCHEMA = {'fields': [{'name': 'id', 'type': 'integer'}, {'name': 'age', 'type': 'integer'}, {'name': 'name', 'type': 'string'}] }

# Open from WEB save to SQL database
table = Table(SOURCE, schema=SCHEMA)
table.save('articles', backend='sql', engine=db)

# Open from SQL save to DRIVE
table = Table('articles', backend='sql', engine=db)
table.schema.save('tmp/articles.json')
table.save('tmp/articles.csv')

# Open from DRIVE print to CONSOLE
table = Table('tmp/articles.csv', schema='tmp/articles.json')
print(table.read(keyed=True))
# Will print
# [{'id': 1, 'age': 39, 'name': 'Paul'}, {'id': 2, 'age': 23, 'name': 'Jimmy'}, {'id': 3, 'age': 36, 'name': 'Jane'}, {'id': 4, 'age': 28, 'name': 'Judy'}]
```

Another one with processors and schema inferring:
```python
import sqlalchemy as sa
from pprint import pprint
from jsontableschema import Table

# Data source
SOURCE = 'https://raw.githubusercontent.com/okfn/jsontableschema-py/master/data/data_infer.csv'

# Create SQL database
db = sa.create_engine('sqlite://')

# Data processor
def skip_under_30(erows):
    for number, headers, row in erows:
        krow = dict(zip(headers, row))
        if krow['age'] >= 30:
            yield (number, headers, row)

# Work with table
table = Table(SOURCE, post_convert=[skip_under_30])
table.schema.save('tmp/persons.json') # Save INFERRED schema
table.save('persons', backend='sql', engine=db) # Save data to SQL
table.save('tmp/persons.csv')  # Save data to DRIVE

# Check the result
pprint(Table('persons', backend='sql', engine=db).read(keyed=True))
pprint(Table('tmp/persons.csv').read(keyed=True))
# Will print (twice)
# [{'age': 39, 'id': 1, 'name': 'Paul'},
#  {'age': 36, 'id': 3, 'name': 'Jane'}]
```

### CODE REVIEW

**Comment by roll** [comment]
@pwalsh 
@zhenyab 
@yotammanor
PR is ready for comments

**Comment by zhenyab** [comment]
I can't check the quality of python code, but the concept of decoupling loaders and parsers in tabulator is great. And tabulator itself is very good idea.

**Comment by roll** [comment]
@danfowler 
Forgot to ping to check the user interface. Already decided with Paul use `Table(..., headers=1)` instead of `Table(..., headers='row1')` but may be something else is confusing?

**Comment by roll** [comment]
@zhenyab 
How doable this processing protocol based on generators in JavaScript?

**Comment by zhenyab** [comment]
@roll To be honest never used yet generators, and can't say how it is doable or not, but generators is kind of iterators, so implementation will be close to the python one.

**Pull request merged**
